### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by pnispero** [Hexotical/WaveformReaderAsyn#1]
## Overall
Was able to run successfully, saw that the waveform is reading in correctly through asyn, and written to waveform record correctly.
Confirmed through plot in pydm display that the input waveform matches output waveform. 
Code formatting looks good, comments are resourceful. 
### WaveformReader.cpp
1) ``` void WaveformReader::streamInit() ```
The variable ``` asynStatus status; ``` isn't used, I recommend printing the status if any errors occur like
``` if (status == asynError) { std::cout << status } ```
 Or, you could make the functions return type asynStatus, which is how I saw it done in mps central node
2) ``` void WaveformReader::streamTask() ```
In the first try catch statement when creating the stream ```stm = IStream::create(p->findByName(streamInit));```
It'd be useful to print the error ```std::cerr << e.what() << std::endl;```
3) For the iocShell commands, I reccommend adding a _printHelp()_ function available to users, so they won't have to look at the code to figure out what shell commands are available. 
### waveform.template
1) The PV names may need to change to adhere to SLACs PV naming convention https://confluence.slac.stanford.edu/display/LCLSControls/LCLS+Naming+Conventions
Mainly just convert the names to all capital letters.

**Comment by Hexotical** [comment]
Addressed problems in commit [d123e09](https://github.com/Hexotical/WaveformReaderAsyn/commit/d123e097e60f8ccbf73cc4706f3f04cb5aa32c26)
